# R/novo_boot.R
# Novometric bootstrap CI from a fixed 2x2 confusion matrix.
# Based on the NOVOboot methodology: Yarnold (2020); Yarnold & Soltysik (2016).
#
# Key design:
#   Model distribution    - resampling paired (actual, predicted) rows;
#                           preserves the observed joint distribution.
#   Chance distribution   - independently resampling actual and predicted
#                           labels; breaks association (pure null).
#   p-value per replicate - exact Fisher 2x2 for every replicate confusion.
#   No model refitting.   - operates entirely on the observed confusion counts.

# ---- S3 generic --------------------------------------------------------------

#' Novometric bootstrap CI from a fixed 2x2 confusion matrix
#'
#' Estimates the precision of an observed binary classification effect by
#' comparing model and chance distributions via permutation/resampling bootstrap.
#' Based on the NOVOboot methodology (Yarnold 2020; Yarnold & Soltysik 2016).
#'
#' \strong{Fixed-confusion bootstrap:} This function samples from the observed
#' confusion matrix structure.  It does not refit the model and does not
#' estimate model-selection variability.  The model distribution is generated
#' by resampling paired (actual, predicted) rows; the chance distribution is
#' generated by independently resampling actual and predicted labels, breaking
#' their association.  Novometric significance (Axiom 1) is declared when the
#' 95\% confidence intervals for model and chance ESS do not overlap.
#'
#' \strong{S3 dispatch:}
#' \itemize{
#'   \item \code{novo_boot_ci.default}  -  accepts a 2\ifelse{html}{\out{&times;}}{\eqn{\times}}2 integer matrix directly.
#'   \item \code{novo_boot_ci.oda_fit}  -  extracts the training confusion from a
#'     binary \code{oda_fit} object.  Errors for multiclass fits.
#'   \item \code{novo_boot_ci.cta_tree}  -  uses the stored \code{training_confusion}
#'     matrix from a \code{cta_tree} object.  Errors for no-tree fits or non-binary.
#'     When \code{node_id} is supplied, uses the class counts from that specific
#'     terminal node instead of the full-tree confusion.
#'   \item \code{novo_boot_ci.cta_ort}  -  derives the full-LORT 2\ifelse{html}{\out{&times;}}{\eqn{\times}}2 confusion by
#'     summing \code{strata$class_counts} over all terminal strata.
#'     When \code{stratum_id} is supplied, uses the class counts from that single
#'     terminal stratum instead.
#' }
#'
#' @param x A 2x2 integer matrix (rows = actual class, columns = predicted
#'   class) when using the default method.  For S3 methods, a fitted model
#'   object (\code{oda_fit}, \code{cta_tree}, or \code{cta_ort}).
#'   The \code{[actual, predicted]} convention matches \code{training_confusion}
#'   in \code{cta_tree} and \code{oda_confusion()}.
#'   Use \code{byrow = TRUE} when constructing with \code{matrix()}.
#' @param nboot Number of bootstrap replicates.  Default 5000.
#' @param seed Integer seed passed to \code{set.seed()}, or \code{NULL} to
#'   use the current RNG state.  Use a fixed seed for reproducibility.
#' @param sample_frac Fraction of \code{n} to sample per replicate (with
#'   replacement).  Default 0.5, matching NOVOboot.
#' @param probs Quantile probability levels for the summary table.
#' @param alternative Direction for exact Fisher p-values: \code{"two.sided"}
#'   (default), \code{"greater"}, or \code{"less"}.
#' @param node_id Integer node id of a \emph{terminal} (leaf) node in a
#'   \code{cta_tree}.  When supplied, the bootstrap operates on the class counts
#'   for that single terminal node rather than the full-tree training confusion.
#'   Only valid for \code{novo_boot_ci.cta_tree}.
#' @param stratum_id Integer stratum id from \code{cta_ort$strata}.  When
#'   supplied, the bootstrap operates on the class counts for that single
#'   terminal LORT stratum rather than the full-LORT confusion.  Only valid for
#'   \code{novo_boot_ci.cta_ort}.
#' @param weighted Logical.  When \code{node_id} or \code{stratum_id} is
#'   supplied, \code{weighted = TRUE} uses case-weighted class counts
#'   (\code{class_counts_weighted}) and \code{weighted = FALSE} (default) uses
#'   raw integer counts (\code{class_counts_raw}).  Ignored for full-tree paths.
#' @param ... Additional arguments (currently unused).
#'
#' @return An object of class \code{novo_boot_ci}, a list with:
#' \describe{
#'   \item{\code{call}}{The matched call.}
#'   \item{\code{confusion}}{Input confusion matrix (integer, 2x2).}
#'   \item{\code{n}}{Total observations (\code{sum(x)}).}
#'   \item{\code{k}}{Observations sampled per replicate
#'     (\code{round(sample_frac * n)}).}
#'   \item{\code{nboot}, \code{sample_frac}, \code{probs},
#'     \code{alternative}}{Input parameters.}
#'   \item{\code{has_zero_cells}}{Logical; \code{TRUE} if any cell of \code{x}
#'     is zero.  Does not prevent computation; NA propagates for affected
#'     metrics.}
#'   \item{\code{observed}}{Data frame with one row per metric.  Columns:
#'     \code{metric}, \code{value}.  Reports observed (not bootstrap) values
#'     of sensitivity, specificity, mean_pac, ess, odds_ratio, and risk_ratio
#'     from the input confusion matrix.}
#'   \item{\code{model}}{Data frame (\code{nboot} rows).  Per-replicate model
#'     bootstrap metrics: \code{sensitivity}, \code{specificity},
#'     \code{mean_pac}, \code{ess} (all in \%), \code{odds_ratio},
#'     \code{risk_ratio}, \code{p_value}.  \code{NA} for undefined OR/RR.}
#'   \item{\code{chance}}{Data frame (\code{nboot} rows).  Same columns as
#'     \code{model}; generated by independently resampling actual and predicted
#'     labels (null of no classification association).}
#'   \item{\code{quantiles}}{Data frame (\code{length(probs)} rows).  Quantiles
#'     of each metric for model and chance, including \code{p_value}.}
#'   \item{\code{ci}}{Data frame (one row per metric).  95\% CI bounds for
#'     model and chance (2.5th and 97.5th percentiles).  Columns:
#'     \code{metric}, \code{model_lower}, \code{model_upper},
#'     \code{chance_lower}, \code{chance_upper}, \code{overlap}.}
#'   \item{\code{significant}}{Logical.  \code{TRUE} if the ESS model 95\% CI
#'     lower bound exceeds the ESS chance 95\% CI upper bound  -  novometric
#'     Axiom 1 CI non-overlap criterion.}
#'   \item{\code{source_type}}{Character.  Evidence provenance tag:
#'     \code{"matrix"} (default method), \code{"oda_fit"},
#'     \code{"cta_tree"}, \code{"cta_tree_node"}, \code{"cta_ort"},
#'     or \code{"cta_ort_stratum"}.}
#'   \item{\code{source_id}}{Integer or \code{NA}.  Node id or stratum id when
#'     the evidence came from a specific sub-unit; \code{NA} for full-tree and
#'     matrix paths.}
#'   \item{\code{weighted}}{Logical or \code{NA}.  \code{TRUE} when weighted
#'     class counts were used; \code{FALSE} when raw counts were used;
#'     \code{NA} for the default matrix path (provenance unknown).}
#' }
#'
#' @references
#' Yarnold PR (2020). Reformulating the First Axiom of Novometric Theory:
#' Assessing Minimum Sample Size in Experimental Design.
#' \emph{Optimal Data Analysis} \bold{9}, 7--8.
#'
#' Yarnold PR, Soltysik RC (2016). \emph{Maximizing Predictive Accuracy}.
#' ODA Books.
#'
#' @examples
#' # Default method: pass a 2x2 matrix directly
#' conf <- matrix(c(146, 40,
#'                   36, 33), nrow = 2, byrow = TRUE)
#' ci <- novo_boot_ci(conf, nboot = 200L, seed = 42L)
#' ci$significant
#' print(ci)
#'
#' @export
novo_boot_ci <- function(x, ...) UseMethod("novo_boot_ci")

#' @rdname novo_boot_ci
#' @export
novo_boot_ci.default <- function(x,
                                  nboot       = 5000L,
                                  seed        = NULL,
                                  sample_frac = 0.5,
                                  probs       = c(0, .025, .05, .25, .5, .75, .95, .975, 1),
                                  alternative = c("two.sided", "greater", "less"),
                                  ...) {

  cl          <- match.call()
  alternative <- match.arg(alternative)

  # ---- Input validation -------------------------------------------------------
  if (!is.matrix(x) || !identical(dim(x), c(2L, 2L)) ||
      (!is.numeric(x) && !is.integer(x)))
    stop("'x' must be a 2x2 numeric matrix (rows = actual, cols = predicted).",
         call. = FALSE)
  if (anyNA(x) || any(!is.finite(x)))
    stop("'x' must be finite with no NA.", call. = FALSE)
  if (any(x < 0))
    stop("'x' must have non-negative counts.", call. = FALSE)

  xi <- round(x)
  if (!isTRUE(all.equal(as.numeric(x), as.numeric(xi), tolerance = 1e-9)))
    warning("'x' has non-integer counts; values were rounded.", call. = FALSE)
  storage.mode(xi) <- "integer"

  n <- sum(xi)
  if (n <= 0L)
    stop("'x' must have total n > 0.", call. = FALSE)

  nboot <- as.integer(nboot[1L])
  if (is.na(nboot) || nboot < 1L)
    stop("'nboot' must be a positive integer.", call. = FALSE)

  if (!is.null(seed)) set.seed(seed)

  has_zero_cells <- any(xi == 0L)

  # ---- Observed metrics from input confusion ----------------------------------
  observed_df <- .novo_observed(xi)

  # ---- Expand confusion to observation vectors --------------------------------
  # Convention: x[1,1]=TN  x[1,2]=FP
  #             x[2,1]=FN  x[2,2]=TP
  TN <- xi[1L, 1L]; FP <- xi[1L, 2L]
  FN <- xi[2L, 1L]; TP <- xi[2L, 2L]

  actual    <- c(rep(0L, TN + FP), rep(1L, FN + TP))
  predicted <- c(rep(0L, TN), rep(1L, FP),
                 rep(0L, FN), rep(1L, TP))

  k <- as.integer(round(sample_frac * n))
  if (k < 2L)
    stop("sample_frac too small: k = ", k, " (need >= 2).", call. = FALSE)

  # ---- Pre-shuffle (matching NOVOboot structure) ------------------------------
  perm        <- sample.int(n)
  actual_s    <- actual[perm]
  predicted_s <- predicted[perm]

  # ---- Pre-allocate -----------------------------------------------------------
  # rows of _mat: TN-rep, FP-rep, FN-rep, TP-rep per bootstrap replicate
  model_mat  <- matrix(0L, 4L, nboot)
  chance_mat <- matrix(0L, 4L, nboot)
  model_p    <- numeric(nboot)
  chance_p   <- numeric(nboot)
  conf_tmp   <- matrix(0L, 2L, 2L)   # reused each iteration  -  no allocation

  # ---- Bootstrap loop ---------------------------------------------------------
  for (i in seq_len(nboot)) {

    # Model: resample k paired rows from first k of the shuffled observations.
    # Preserves the observed (actual, predicted) joint distribution.
    idx <- sample.int(k, k, replace = TRUE)
    a   <- actual_s[idx]
    p   <- predicted_s[idx]
    model_mat[1L, i] <- tn <- sum(a == 0L & p == 0L)
    model_mat[2L, i] <- fp <- sum(a == 0L & p == 1L)
    model_mat[3L, i] <- fn <- sum(a == 1L & p == 0L)
    model_mat[4L, i] <- tp <- sum(a == 1L & p == 1L)
    conf_tmp[1L, 1L] <- tn; conf_tmp[1L, 2L] <- fp
    conf_tmp[2L, 1L] <- fn; conf_tmp[2L, 2L] <- tp
    model_p[i] <- .fisher_p(conf_tmp, alternative)

    # Chance: independently resample actual and predicted  -  breaks pairing.
    # Generates the null distribution of no classification association.
    idx_a <- sample.int(k, k, replace = TRUE)
    idx_p <- sample.int(k, k, replace = TRUE)
    a2    <- actual_s[idx_a]
    p2    <- predicted_s[idx_p]
    chance_mat[1L, i] <- tn <- sum(a2 == 0L & p2 == 0L)
    chance_mat[2L, i] <- fp <- sum(a2 == 0L & p2 == 1L)
    chance_mat[3L, i] <- fn <- sum(a2 == 1L & p2 == 0L)
    chance_mat[4L, i] <- tp <- sum(a2 == 1L & p2 == 1L)
    conf_tmp[1L, 1L] <- tn; conf_tmp[1L, 2L] <- fp
    conf_tmp[2L, 1L] <- fn; conf_tmp[2L, 2L] <- tp
    chance_p[i] <- .fisher_p(conf_tmp, alternative)
  }

  # ---- Vectorized metric computation ------------------------------------------
  model_df  <- .novo_metrics(model_mat,  model_p)
  chance_df <- .novo_metrics(chance_mat, chance_p)

  # ---- Quantile table ---------------------------------------------------------
  quantiles_df <- .novo_quantiles(model_df, chance_df, probs)

  # ---- CI data frame (fixed 95% bounds: 2.5th / 97.5th) ----------------------
  ci_df <- .novo_ci(model_df, chance_df)

  # ---- Novometric significance (Axiom 1: ESS CI non-overlap) -----------------
  ess_row    <- ci_df$metric == "ess"
  significant <- isTRUE(ci_df$model_lower[ess_row] > ci_df$chance_upper[ess_row])

  structure(
    list(
      call           = cl,
      confusion      = xi,
      n              = n,
      k              = k,
      nboot          = nboot,
      sample_frac    = sample_frac,
      probs          = probs,
      alternative    = alternative,
      has_zero_cells = has_zero_cells,
      observed       = observed_df,
      model          = model_df,
      chance         = chance_df,
      quantiles      = quantiles_df,
      ci             = ci_df,
      significant    = significant,
      source_type    = "matrix",
      source_id      = NA_character_,
      weighted       = NA
    ),
    class = c("novo_boot_ci", "list")
  )
}

# ---- print method ------------------------------------------------------------

#' @export
print.novo_boot_ci <- function(x, ...) {
  cat("Novometric fixed-confusion bootstrap\n")
  cat(sprintf("  n = %d   k = %d   nboot = %d   sample_frac = %.2f\n",
              x$n, x$k, x$nboot, x$sample_frac))
  if (x$has_zero_cells)
    cat("  [note: input confusion has one or more zero cells]\n")
  cat("\nConfusion matrix (actual x predicted):\n")
  print(x$confusion)

  obs_ess <- x$observed$value[x$observed$metric == "ess"]
  obs_pac <- x$observed$value[x$observed$metric == "mean_pac"]
  if (length(obs_ess) == 1L && length(obs_pac) == 1L)
    cat(sprintf("\nObserved:  ESS = %.2f%%   Mean PAC = %.2f%%\n",
                obs_ess, obs_pac))

  cat("\n95% CI (2.5% -- 97.5%):\n")
  for (met in c("ess", "mean_pac", "sensitivity", "specificity")) {
    row <- x$ci[x$ci$metric == met, , drop = FALSE]
    if (nrow(row) == 0L) next
    lab <- switch(met,
      ess         = "ESS (%)",
      mean_pac    = "Mean PAC (%)",
      sensitivity = "Sensitivity (%)",
      specificity = "Specificity (%)"
    )
    cat(sprintf("  %-17s  Model [%6.2f, %6.2f]  Chance [%6.2f, %6.2f]  Overlap: %s\n",
      lab,
      row$model_lower,  row$model_upper,
      row$chance_lower, row$chance_upper,
      row$overlap
    ))
  }
  cat(sprintf("\nNovometric significance (ESS CI non-overlap): %s\n", x$significant))
  invisible(x)
}

# ---- S3 methods for fitted objects ------------------------------------------

#' @rdname novo_boot_ci
#' @export
novo_boot_ci.oda_fit <- function(x,
                                  nboot       = 5000L,
                                  seed        = NULL,
                                  sample_frac = 0.5,
                                  probs       = c(0, .025, .05, .25, .5, .75, .95, .975, 1),
                                  alternative = c("two.sided", "greater", "less"),
                                  ...) {
  if (!inherits(x, "oda_fit_binary"))
    stop("novo_boot_ci.oda_fit: only binary ODA fits are supported. ",
         "NOVOboot requires a 2x2 confusion matrix.", call. = FALSE)
  conf <- x$confusion
  if (is.null(conf) || is.null(conf$TP))
    stop("novo_boot_ci.oda_fit: no training confusion stored on fit.", call. = FALSE)
  m <- matrix(c(conf$TN, conf$FP,
                conf$FN, conf$TP),
              nrow = 2L, byrow = TRUE)
  result <- novo_boot_ci.default(m, nboot = nboot, seed = seed,
                                  sample_frac = sample_frac, probs = probs,
                                  alternative = alternative, ...)
  result$source_type <- "oda_fit"
  result$source_id   <- NA_character_
  result$weighted    <- FALSE   # $confusion always holds raw integer counts
  result
}

#' @rdname novo_boot_ci
#' @export
novo_boot_ci.cta_tree <- function(x,
                                   nboot       = 5000L,
                                   seed        = NULL,
                                   sample_frac = 0.5,
                                   probs       = c(0, .025, .05, .25, .5, .75, .95, .975, 1),
                                   alternative = c("two.sided", "greater", "less"),
                                   node_id     = NULL,
                                   weighted    = FALSE,
                                   ...) {

  if (!is.null(node_id)) {
    # ---- Terminal-node path (path D) ----------------------------------------
    node_id <- as.integer(node_id[1L])
    nd <- x$nodes[[node_id]]
    if (is.null(nd))
      stop("novo_boot_ci.cta_tree: node_id ", node_id,
           " not found in tree.", call. = FALSE)
    if (!isTRUE(nd$leaf))
      stop("novo_boot_ci.cta_tree: node_id ", node_id,
           " is not a terminal (leaf) node.  NOVOboot requires a leaf node.",
           call. = FALSE)
    cc <- if (isTRUE(weighted)) nd$class_counts_weighted
          else                  nd$class_counts_raw
    if (is.null(cc) || length(cc) == 0L)
      stop("novo_boot_ci.cta_tree: node ", node_id,
           " has no class counts.", call. = FALSE)
    mc <- as.integer(nd$majority_class)
    m  <- .node_counts_to_confusion(cc, mc)
    result <- novo_boot_ci.default(m, nboot = nboot, seed = seed,
                                    sample_frac = sample_frac, probs = probs,
                                    alternative = alternative, ...)
    result$source_type <- "cta_tree_node"
    result$source_id   <- node_id
    result$weighted    <- isTRUE(weighted)
    return(result)
  }

  # ---- Full-tree path (path C) ------------------------------------------------
  if (isTRUE(x$no_tree))
    stop("novo_boot_ci.cta_tree: no tree was found (no_tree = TRUE). ",
         "No confusion matrix available.", call. = FALSE)
  m <- x$training_confusion
  if (is.null(m))
    stop("novo_boot_ci.cta_tree: training_confusion is NULL.", call. = FALSE)
  if (!identical(dim(m), c(2L, 2L)))
    stop("novo_boot_ci.cta_tree: training_confusion is not 2x2. ",
         "NOVOboot requires a binary classification model.", call. = FALSE)
  result <- novo_boot_ci.default(m, nboot = nboot, seed = seed,
                                  sample_frac = sample_frac, probs = probs,
                                  alternative = alternative, ...)
  result$source_type <- "cta_tree"
  result$source_id   <- NA_character_
  result$weighted    <- FALSE   # training_confusion is always raw integer counts
  result
}

#' @rdname novo_boot_ci
#' @export
novo_boot_ci.cta_ort <- function(x,
                                  nboot       = 5000L,
                                  seed        = NULL,
                                  sample_frac = 0.5,
                                  probs       = c(0, .025, .05, .25, .5, .75, .95, .975, 1),
                                  alternative = c("two.sided", "greater", "less"),
                                  stratum_id  = NULL,
                                  weighted    = FALSE,
                                  ...) {
  st <- x$strata
  if (is.null(st) || nrow(st) == 0L)
    stop("novo_boot_ci.cta_ort: strata absent or empty. ",
         "Cannot derive LORT confusion matrix.", call. = FALSE)

  if (!is.null(stratum_id)) {
    # ---- Single-stratum path (path F) ---------------------------------------
    stratum_id <- as.integer(stratum_id[1L])
    row_idx <- which(st$stratum_id == stratum_id)
    if (length(row_idx) == 0L)
      stop("novo_boot_ci.cta_ort: stratum_id ", stratum_id,
           " not found in strata.", call. = FALSE)
    row_idx <- row_idx[1L]
    cc  <- st$class_counts[[row_idx]]
    if (is.null(cc) || length(cc) == 0L)
      stop("novo_boot_ci.cta_ort: stratum ", stratum_id,
           " has no class counts.", call. = FALSE)
    mc <- as.integer(st$terminal_class[row_idx])
    m  <- .node_counts_to_confusion(cc, mc)
    result <- novo_boot_ci.default(m, nboot = nboot, seed = seed,
                                    sample_frac = sample_frac, probs = probs,
                                    alternative = alternative, ...)
    result$source_type <- "cta_ort_stratum"
    result$source_id   <- stratum_id
    result$weighted    <- isTRUE(weighted)
    return(result)
  }

  # ---- Full-LORT path (path E) -----------------------------------------------
  # Accumulate full-LORT confusion from per-terminal class_counts.
  # Convention: conf[actual+1, predicted+1] (rows=actual, cols=predicted).
  m <- matrix(0L, 2L, 2L)
  for (i in seq_len(nrow(st))) {
    p  <- as.integer(st$terminal_class[i]) + 1L   # predicted col (1-indexed)
    cc <- st$class_counts[[i]]                     # named int vector e.g. c("0"=18, "1"=2)
    if (is.null(cc) || length(cc) == 0L) next
    for (cls_name in names(cc)) {
      a <- as.integer(cls_name) + 1L               # actual row (1-indexed)
      if (a < 1L || a > 2L || p < 1L || p > 2L) next
      m[a, p] <- m[a, p] + as.integer(cc[cls_name])
    }
  }
  if (sum(m) == 0L)
    stop("novo_boot_ci.cta_ort: accumulated confusion has zero total count. ",
         "Check strata class_counts.", call. = FALSE)
  result <- novo_boot_ci.default(m, nboot = nboot, seed = seed,
                                  sample_frac = sample_frac, probs = probs,
                                  alternative = alternative, ...)
  result$source_type <- "cta_ort"
  result$source_id   <- NA_character_
  result$weighted    <- FALSE   # class_counts in strata are raw integer counts
  result
}

# ---- internal helpers --------------------------------------------------------

# .node_counts_to_confusion(cc, majority_class)
#
# Build a 2x2 integer confusion matrix from a leaf node's or stratum's class
# counts and majority (predicted) class.  Because a leaf predicts ALL its
# observations as majority_class, the resulting 2x2 always has one empty column
# (has_zero_cells = TRUE); novo_boot_ci.default handles this gracefully.
#
# cc            : named integer (or numeric) vector; names are string class
#                 labels (e.g. c("0"=18, "1"=2)).
# majority_class: integer (0 or 1) - the predicted class for every obs.
# Returns a 2x2 integer matrix with rows = actual class, cols = predicted class.
.node_counts_to_confusion <- function(cc, majority_class) {
  mc <- as.integer(majority_class)
  p  <- mc + 1L                        # predicted column, 1-indexed
  if (p < 1L || p > 2L)
    stop(".node_counts_to_confusion: majority_class must be 0 or 1.",
         call. = FALSE)
  m <- matrix(0L, 2L, 2L)
  for (cls_name in names(cc)) {
    a <- as.integer(cls_name) + 1L     # actual row, 1-indexed
    if (a < 1L || a > 2L) next
    m[a, p] <- m[a, p] + as.integer(cc[[cls_name]])
  }
  m
}

# Observed metrics from the input confusion matrix.
# Returns a data.frame with metric / value columns.
.novo_observed <- function(xi) {
  TN <- xi[1L, 1L]; FP <- xi[1L, 2L]
  FN <- xi[2L, 1L]; TP <- xi[2L, 2L]
  sens_f <- if ((TP + FN) > 0L) TP / (TP + FN) else NA_real_
  spec_f <- if ((TN + FP) > 0L) TN / (TN + FP) else NA_real_
  mpac_f <- (sens_f + spec_f) / 2
  ess    <- 100 * (mpac_f - 0.5) / 0.5
  or     <- (TP * TN) / (FP * FN)
  rr     <- (TP / (TP + FP)) / (FN / (FN + TN))
  or     <- if (is.finite(or)) or else NA_real_
  rr     <- if (is.finite(rr)) rr else NA_real_
  data.frame(
    metric = c("sensitivity", "specificity", "mean_pac", "ess",
               "odds_ratio", "risk_ratio"),
    value  = c(sens_f * 100, spec_f * 100, mpac_f * 100, ess, or, rr),
    stringsAsFactors = FALSE
  )
}

# Safe Fisher exact p for a pre-allocated 2x2 matrix.
# Returns NA_real_ when any margin is zero (degenerate table).
.fisher_p <- function(m, alternative) {
  if (m[1L,1L] + m[1L,2L] == 0L || m[2L,1L] + m[2L,2L] == 0L ||
      m[1L,1L] + m[2L,1L] == 0L || m[1L,2L] + m[2L,2L] == 0L)
    return(NA_real_)
  fisher.test(m, alternative = alternative)$p.value
}

# Vectorized metric computation from a 4 x nboot integer count matrix.
# Row order: TN, FP, FN, TP (matching the tabulation in the loop above).
.novo_metrics <- function(mat, p_vec) {
  c_tn <- mat[1L, ]; c_fp <- mat[2L, ]
  c_fn <- mat[3L, ]; c_tp <- mat[4L, ]

  sens_f <- c_tp / (c_tp + c_fn)       # fraction; NA when denom = 0
  spec_f <- c_tn / (c_tn + c_fp)       # fraction; NA when denom = 0
  mpac_f <- (sens_f + spec_f) / 2
  # Canonical ESS formula: oda_ess_from_meanpac(mpac, chance=0.5)
  ess    <- 100 * (mpac_f - 0.5) / 0.5

  # Diagnostic OR = (TP*TN) / (FP*FN); RR = PPV / FOR
  or  <- (c_tp * c_tn) / (c_fp * c_fn)
  rr  <- (c_tp / (c_tp + c_fp)) / (c_fn / (c_fn + c_tn))
  or[!is.finite(or)] <- NA_real_
  rr[!is.finite(rr)] <- NA_real_

  data.frame(
    sensitivity = sens_f * 100,
    specificity = spec_f * 100,
    mean_pac    = mpac_f * 100,
    ess         = ess,
    odds_ratio  = or,
    risk_ratio  = rr,
    p_value     = p_vec,
    stringsAsFactors = FALSE
  )
}

# Quantile table: length(probs) rows, one column pair per metric.
.novo_quantiles <- function(model_df, chance_df, probs) {
  .q <- function(df, sfx) {
    cols <- lapply(df, function(v) quantile(v, probs = probs, na.rm = TRUE))
    result <- as.data.frame(cols, check.names = FALSE)
    setNames(result, paste0(names(df), sfx))
  }
  data.frame(prob = probs, .q(model_df, "_model"), .q(chance_df, "_chance"),
             check.names = FALSE)
}

# CI data frame: one row per metric, fixed 95% bounds (2.5th / 97.5th).
# Column names: metric, model_lower, model_upper, chance_lower, chance_upper, overlap.
.novo_ci <- function(model_df, chance_df) {
  .p <- function(df, prob)
    vapply(df, function(v) quantile(v, prob, na.rm = TRUE), numeric(1L))
  lo_m <- .p(model_df,  0.025); hi_m <- .p(model_df,  0.975)
  lo_c <- .p(chance_df, 0.025); hi_c <- .p(chance_df, 0.975)
  data.frame(
    metric       = names(model_df),
    model_lower  = unname(lo_m),
    model_upper  = unname(hi_m),
    chance_lower = unname(lo_c),
    chance_upper = unname(hi_c),
    overlap      = unname(lo_m <= hi_c & lo_c <= hi_m),
    stringsAsFactors = FALSE
  )
}
